AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "**\\lib\\ruby\\**\\*"
  NewCops: enable
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
