AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - "**\\lib\\ruby\\**\\*"
  NewCops: enable
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: true
Style/GlobalVars:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: true
Style/RedundantReturn:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true
Style/Documentation:
  Enabled: true
